# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171123_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='visible',
            new_name='publish',
        ),
    ]
